### ISSUE TITLE
CI action repo checkout python script get-prs can't find github module

### ISSUE THREAD

**Issue by axel-h** [seL4/sel4bench#24]
The "`Freeze Code`" -> "`Repo checkout`" step shows an error that the python script `get-prs` can't find the module `github`. See in https://github.com/seL4/sel4bench/runs/5187557758?check_suite_focus=true for an example. The error is ignored, but I think the "test with" features for PR is broken due to this eventually.

```
Repo checkout
  Starting repo checkout on branch master with manifest master.xml:
  Downloading manifest from https://github.com/seL4/sel4bench-manifest
  
  repo has been initialized in /home/runner/work/sel4bench/sel4bench
  repo sync has finished successfully.
  Fetching refs/heads/master from github.com/seL4/sel4bench.git
  Traceback (most recent call last):
    File "/home/runner/work/_actions/seL4/ci-actions/master/js/../scripts/get-prs", line [21](https://github.com/seL4/sel4bench/runs/5187557758?check_suite_focus=true#step:2:21), in <module>
      from github import Github
  ModuleNotFoundError: No module named 'github'
```

**Comment by axel-h** [comment]
Seem we need a dedicated docker container for `ci-actions/repo-checkout` that has `PyGithub`. I wonder if a generic docker base container for all github ci actions build from "`trustworthysystems/sel4:latest` + `PyGithub`" makes sense, something like `trustworthysystems/sel4-github-ci`"

**Comment by lsf37** [comment]
Ok, I figured it out: surveying the workflows so far, we haven't actually used the repo-checkout action for pull requests yet, so the code that needs that dependency was not executed there. We only need it if we want to chain multiple actions together and that has so far mostly happened in the deployment workflows. PR actions that call the same script do install the dependency already.

For e.g. sel4test PRs, the repo checkout is part of the hardware build action. We could probably simplify the PR workflow in sel4bench to do the same as sel4test (i.e. just leave out the Freeze Code step), because there aren't any other parts of the workflow that check out anything and where it would be critical that they see the exact same versions, but I think I prefer keeping the workflow file as close to the deployment workflow as possible (it would be nice to merge them, but doing that is fairly messy).

I've added the module to the setup part of `repo-checkout`, which should fix the problem.
